### ISSUE TITLE
Leches controls multiply when page is revisited in Cientos docs

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/leches#62]
## Description

[In Cientos docs](https://cientos.tresjs.org/guide/abstractions/lensflare.html), when navigating *back to* a page with Leches controls, the controls are duplicated – and reduplicated on every subsequent visit until the page is reloaded.

https://github.com/Tresjs/leches/assets/20469369/88e6e989-8e86-4e87-bda6-d7368d59a78a

## Reproduction

1. Go to [Lensflare](https://cientos.tresjs.org/guide/abstractions/lensflare.html)
2. See 1 control for scale
3. Click on 'MouseParallax' in the left-hand menu
4. Click on 'Lensflare' in the left-hand menu
5. See 2 controls for scale
6. Click on 'MouseParallax' in the left-hand menu
7. Click on 'Lensflare' in the left-hand menu
8. See 3 controls for scale

## Expected behavior

The controls should not be duplicated.

**Comment by alvarosabu** [comment]
It also happens with HMR, I was about to open a ticket about it. Thanks @andretchen0 for doing it, gonna work on it
