### ISSUE TITLE
Leches causes console warnings to be emitted

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/leches#86]
**Describe the bug**

Adding Leches v0.14.0 to a `<template>` causes a number of warnings to be emitted in the browser console. Additional warnings are emitted if Leches is configured to use a "folder".

Check the StackBlitz below. Here are the warnings emitted by the StackBlitz. Using Firefox/Mac and Chrome/Mac locally.

```
[Vue warn]: Extraneous non-props attributes (role) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
[...]
```

```
Request for font "Roboto" blocked at visibility level 2 (requires 3)
tresjsbasiccdhx7e-ytd5--5173--d3416dfd.local-corp.webcontainer.io
```

**Reproduction**

* See this [Stackblitz](https://stackblitz.com/edit/tresjs-basic-cdhx7e?file=src%2Fcomponents%2FTheExperience.vue) 
* Open the browser console to see warnings.

**Expected behavior**

No warnings for normal use.

**System Info**

From StackBlitz:

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @tresjs/cientos: ^3.5.1 => 3.5.1 
    @tresjs/core: ^3.4.1 => 3.4.1 
    @tresjs/eslint-config-vue: ^0.2.1 => 0.2.1 
    @tresjs/leches: ^0.14.0 => 0.14.0 
    vite: ^4.5.0 => 4.5.0

**Comment by Readpato** [comment]
Hey there! I took a jab on fixing this. 
I managed to solve this error:

> [Vue warn]: Extraneous non-props attributes (role) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.

Replacing the root with a real HTML element of `<ControlInput>` fixed that.

Regarding the other error that I encountered:

> [Vue warn]: expose() should be passed a plain object, received ref. 

This `<ContactShadows>` component belongs to the [Cientos](https://cientos.tresjs.org/) library, maybe we can open an issue over there and try to fix it =]

Last but not least, this error:

> Request for font "Roboto" blocked at visibility level 2 (requires 3)
> tresjsbasiccdhx7e-ytd5--5173--d3416dfd.local-corp.webcontainer.io

Didn't appear when I opened the reproduction code, I even did so many times.  It might be a Stackblitz warning seeing that it mentions webcontainers at the end of the URL? What do you think about this @alvarosabu ?

**Comment by alvarosabu** [comment]
Hi @Readpato thanks for opening this and providing a fix, regarding the ContactShadows there is already a bug opened in cientos. 

Stackblitz does that sometimes, no worries
